name: "AMSExplorer"

on:
  workflow_dispatch:

jobs:
  test-building-devenv-2022:
    name: "Test building by devenv"
    runs-on: ${{ matrix.os }}
    env:
      DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
      SLN_PATH: AMSExplorer.sln
    strategy:
      matrix:
        os: [windows-2022]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Take screenshot
      shell: pwsh
      run: ./take-screenshot.ps1
    - uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: path/to/artifact/world.txt
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
    - name: nuget restore
      shell: cmd
      run: nuget restore AMSExplorer\AMSExplorer.csproj
    - name: devenv setup
      shell: cmd
      run: |
        "%DEVENV_PATH%" /setup
    - name: compile debug
      shell: cmd
      run: |
        "%DEVENV_PATH%" "%SLN_PATH%" /build debug
    - name: compile release
      shell: cmd
      run: |
        "%DEVENV_PATH%" "%SLN_PATH%" /build release
  test-building-msbuild-2022:
    name: "Test building by msbuild"
    runs-on: ${{ matrix.os }}
    env:
      SLN_PATH: AMSExplorer.sln
    strategy:
      matrix:
        os: [windows-2022]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: msbuild restore
      shell: cmd
      run: |
        msbuild /t:restore "%SLN_PATH%"
    - name: compile debug
      shell: cmd
      run: |
        msbuild "%SLN_PATH%" /p:Configuration=Debug
    - name: compile release
      shell: cmd
      run: |
        msbuild "%SLN_PATH%" /p:Configuration=Release